### ISSUE TITLE
Replace Fmt implementation by mtl + ConduitT or similar

### ISSUE THREAD

**Issue by roberth** [hercules-ci/canonix#17]
Fmt's combination of computational effects may be weird, but probably not so weird that it can't be done by reusing some stuff from libraries like mtl, pipes, conduit.
This means we get rid of `Free` which wasn't super useful in the first place.
It's worth checking that the chunk output and node reading still nicely interleave. (Assuming #16 is merged)

**Comment by domenkozar** [comment]
This can be closed?

**Comment by roberth** [comment]
Positive, was part of merge of #18
