### ISSUE TITLE
Use ParseError to print out filename/line/error when parse failed

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/canonix#8]

**Comment by domenkozar** [comment]
Doesn't seem like we can do that yet: https://github.com/tree-sitter/haskell-tree-sitter/issues/145

**Comment by roberth** [comment]
I don't think that prevents us from doing some bounds checking ourselves before creating the `ANode`s

**Comment by domenkozar** [comment]
Since https://github.com/tree-sitter/haskell-tree-sitter/pull/147 is landing soon, I'd prefer to wait on that.

**Comment by robrix** [comment]
@domenkozar: I’m hoping to land that PR today 🤞🏻

Will you also need a hackage release before you can move forward? If so, I can arrange one today, but otherwise I was planning on waiting a bit and pushing out a few updates at once.

**Comment by domenkozar** [comment]
@robrix thanks. We pin [with git](https://github.com/hercules-ci/canonix/blob/master/nix/src/haskell-tree-sitter.nix) for the moment so I'm waiting for PR to be merged (so it's stabilized).

**Comment by robrix** [comment]
@domenkozar the PR has landed! 🚀🦅

**Comment by domenkozar** [comment]
Fixed in master.
